### ISSUE TITLE
Only show stops in service

### ISSUE THREAD

**Issue by tklovett** [jonahgrant/mbus#5]
You can reduce visual clutter by only showing the stops that are currently being serviced. From the Routes data, you can pull out the full set of IDs of stops that are in service.

**Comment by jonahgrant** [comment]
Good idea.  I messed around with this yesterday but it caused all sorts of lags and delays.  I'm moving all models to core data entities to persist most objects.  That will make this work without taking up an obscene amount of memory.

**Comment by tklovett** [comment]
:+1:

**Comment by jonahgrant** [comment]
Done!
