### ISSUE TITLE
Consider only showing stops when zoomed in

### ISSUE THREAD

**Issue by tklovett** [jonahgrant/mbus#6]
On mbus.pts.umich.edu, I only show stop markers on the map when the user zooms in far enough. This helps to reduce visual clutter.

**Comment by jonahgrant** [comment]
Yeah, I want to do this but it's generally looked down upon to add/remove large sets of annotations from MKMapView when region/zoom level changes.

**Comment by tklovett** [comment]
We currently have ~150 stops with a max of ~110 in service at any given time. Does that qualify as a large set of annotations?

**Comment by jonahgrant** [comment]
It varies from device to device with differentiating RAM and CPU levels.

Regardless, I bet I can find a solution.

On Dec 3, 2013, at 10:44 AM, Thomas Lovett notifications@github.com wrote:

We currently have ~150 stops with a max of ~110 in service at any given time. Does that qualify as a large set of annotations?

**Comment by jonahgrant** [comment]
Closing because the Map tab currently only shows buses, while each operating route can present it's own map with it's stops and the buses servicing it.
